# Parameters for the signal generator node
signal_generator:
  ros__parameters:
    type: 1 # 1 for sine wave, 2 for square wave, 3 for sawtooth wave
    amplitude: 0.5 # Amplitude value
    frequency: 2.0 # Frequency value (Hz)
    offset: 0.0 # Offset value (rad)